### ISSUE TITLE
Bot repeates messages sent via discord.

### ISSUE THREAD

**Issue by JzJad** [Mattie112/FactoriGOChatBot#28]
Currently using docker image pr-26 (also used a few others) Anytime a message is sent via discord the bot reads the message from the log and sends it back into discord. May want to have it filter against the chat read from the log to match and ignore on something like.

[CHAT] <server>: [color=#7289DA][Discord].*[/color]

**Comment by Mattie112** [comment]
Thank you. That is probably due to https://github.com/Mattie112/FactoriGOChatBot/pull/25 that changes the default way of sending chat to the server.

This was not an issue before so I can only assume that the commands are not logged but the server chat is. And indeed that will cause problems. I was not able to test it in game yesterday (had some issues) so that is why I didn't release a new version yet. Will fix it ASAP. As a workaround (if you don't care about achievements) you can enable the mode from that PR then it should work as expected.

**Comment by JzJad** [comment]
Wanted to make sure you where aware, have not started with go yet or id make an attempt at a PR, Sadly we are going for achievements (Some friends are new to the game), I did test both modes just to ensure it was just with achievements.

**Comment by Mattie112** [comment]
I wasn't aware yet so thank you. I will leave this open till it is fixed.

Will have to check in the logs the exact format when the 'server' chats to the game and indeed exclude that. Possibly everything that starts with server but it depends on the exact format :)

**Comment by Mattie112** [comment]
If I just manually test it via the CLI (cannot really run the bot from here):

![image](https://github.com/user-attachments/assets/67172270-c804-464b-bd59-74a2830a7c9a)

Shows up in the log like:
```
2024-10-29 09:33:47 [CHAT] <server>: [color=#7289DA][Discord]test123[/color]
```

So I think we should be able to just filter-out anything that starts with `[CHAT] <server>`

**Comment by Mattie112** [comment]
I made something that I hope works, if you can test it that would be great :)

https://github.com/Mattie112/FactoriGOChatBot/pull/29

Binaries at https://github.com/Mattie112/FactoriGOChatBot/actions/runs/11577531992?pr=29

**Comment by Mattie112** [comment]
Allright thanks, then I just need my complete setup to test what is happening exactly. Not sure if am able to do that today due to work, but tomorrow I have time reserved to release the next version :)
