### ISSUE TITLE
Bot online message is repeated

### ISSUE THREAD

**Issue by Mattie112** [Mattie112/FactoriGOChatBot#37]
Not sure why, I thought I fixed the 'repeating' case, but for the bot online message it somehow does not work.

![image](https://github.com/user-attachments/assets/a739d093-c84b-401f-999f-9b0f7cc2b86c)

**Comment by changchiyou** [comment]
The solution in [PR #29](https://github.com/Mattie112/FactoriGOChatBot/pull/29) now filters only CHAT messages from the server that match the pattern `(?m)] (.*): (.*)`:

https://github.com/Mattie112/FactoriGOChatBot/blob/6824784e1375338ee4df082481e4648ec4439689/main.go#L131-L149

Therefore, only the first `console.log` entry is ignored because it matches the regex, while the second entry is not ignored, leading to a loop.

```
2024-11-11 05:34:18 [CHAT] <server>: [color=#7289DA][Discord][happydogismine]: !online[/color]
```

```
2024-11-11 14:57:07 [CHAT] <server>: [color=#7289DA][Discord]FactoriGO Chat Bot is online![/color]
```

**Comment by Mattie112** [comment]
Oh interesting, so the missing `[discorduser]: ` is screwing it up.

Perhaps we should just change the regex to only look for `<server>:` or something.
